version: '3'

volumes:
  db-store:

configs:
  db-config:
    file: ./infra/docker/mysql/my.cnf

services:
  app:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./infra/docker/php-apache/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    environment:
      - UID=${LOCAL_UID:-1000}
      - GID=${LOCAL_GID:-1000}
      - USERNAME=${WHOAMI:-myuser}
      # Please remove this environment variable, after created the Laravel project. Please write in .env
      - LOG_CHANNEL=${LOG_CHANNEL:-daily}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    entrypoint: /usr/local/bin/entrypoint.sh
    command: apache2-foreground

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3306}
        protocol: tcp
        mode: host
    configs:
      - source: db-config
        target: /etc/my.cnf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-rootpassword}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
